### ISSUE TITLE
More or Next button in Linker

### ISSUE THREAD

**Issue by jnoessner** [linkedhumanities/lode#60] opened 2013-07-24 09:46 UTC
If there exist more linking canidates than the ones displayed, it would be useful to be able to load them as well (e.g. by clicking a 'more' button at the bottom of the page).

One example where more linking canidates should exist is http://www.linkedhumanities.com/link/dbpedia/entity:e4967.

**Comment by sztyler** [comment] 2013-07-24 10:33
this ticket is a duplicate of issue #29

**Closed as completed by sztyler** 2013-07-24 10:33 UTC
Labels: enhancement, Linker
