### ISSUE TITLE
More direct way to the linking interfaces

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#2] opened 2013-02-11 21:22 UTC
In the browsing interface, the sameAs Link column lists the symbols for DBpedia and InPhO (and, in the future, more repositories). A click on a grey symbol should lead the user directly to the linking page for the respective repository. For instance, when clicking on the grayed icon for DBpedia, the user should get directly to the DBpedia linking interface.

**Comment by jakob0910** [comment] 2013-02-16 21:19
I implemented this feature but there are still some questions we should clarify.
As we support only DBpedia as linking and enhancement resource at the moment, it is not possible to call the linker or enhancer for e.g. InPho. So, we would only show the grey DBpedia icon if no sameAs link exists.

What happens if an entity is linked to one or more resources? Originally we planned that the colored icon is linked to the external resource but we should also add a direct link to the enhancer (if an implementation exists). That is a bit tricky because we need two links on one image. I solved this with a popover (http://twitter.github.com/bootstrap/javascript.html#popovers). The problem is that this solution requires two clicks and is neither intuitive nor consistent with the implementation for the grey icons...

**Comment by mniepert** [comment] 2013-02-18 17:32
The interim solution with the pop-over looks good, I think. This shouldn't have the highest priority at the moment. Eventually, we might want to run some usability studies with actual users, and compare different versions.

**Comment by mniepert** [comment] 2013-02-18 18:13
There's one thing that's pretty annoying though: Whenever one clicks on the icon and the popover opens, one jumps to the top of the page and has to scroll back.

**Comment by jakob0910** [comment] 2013-02-18 21:36
The "jump to top" issue is now fixed.

Jan suggested to add the option to delete the sameAs relation as third choice.

**Comment by mniepert** [comment] 2013-02-18 23:22
Sounds great!

**Comment by sztyler** [comment] 2013-02-19 00:33
does this problem still exist?

**Comment by mniepert** [comment] 2013-02-19 00:39
No _but_ it's not quite there yet. What's missing is that the pop-overs
disappear when the user clicks somewhere else (I think this is standard
pop-over bahavior, if I'm not mistaken). As of now, each of the pop-overs
stays open.

**Comment by jnoessner** [comment] 2013-02-19 08:04
And you did not include the same functionality on the view page yet(same popup) as we discussed.

**Comment by jnoessner** [comment] 2013-05-07 14:05
Summary: Open issues: Pop-overs must disapear

**Comment by jakob0910** [comment] 2013-07-27 23:15
The pop-over problem should be solved (see issue #42).

**Closed as completed by jakob0910** 2013-07-27 23:15 UTC
Labels: enhancement, Content explorer
