### ISSUE TITLE
entity and thinker

### ISSUE THREAD

**Issue by colinallen** [linkedhumanities/lode#21] opened 2013-02-18 14:16 UTC
A search for 'Frege' gives both these results:

entity:e3038    Gottlob Frege   entity  
thinker:t3038   Gottlob Frege   thinker, Person 

On the InPhO site, these are (I believe) one data record not two.  Is this an InPhO bug or a Lode issue?

**Comment by sztyler** [comment] 2013-02-18 14:59
this is a duplicate of ticket #11

**Comment by mniepert** [comment] 2013-02-18 17:29
Colin: The InPhO RDF file has currently two separate objects, one for thinker and one for entity, with different URIs. As far as I understand, this is because of the internal representation of entities in InPhO and the way the RDF file is created. The solution we are working towards is to "cluster" entities according to sameAs relations, if an RDF file has these relations. If the InPhO RDF file does not store these sameAs relations, however, we cannot do much on our side.

**Comment by sztyler** [comment] 2013-02-25 14:06
duplicate

**Closed as completed by sztyler** 2013-02-25 14:06 UTC
Labels: enhancement, Content explorer
